alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias vim='nvim'
alias firefox='firefox &'
alias path='echo $PATH | tr ":" "\n"'
alias dotfiles='/usr/bin/git --git-dir="$HOME/.dotfiles/" --work-tree="$HOME"'
